-- Active: 1722846932660@@127.0.0.1@3306
DROP DATABASE IF EXISTS `tp_db`;
CREATE DATABASE IF NOT EXISTS `tp_db` DEFAULT CHARACTER SET = 'utf8mb4';
USE tp_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES users (id)
);